aliyun:
  oss:
    file:
      bucketname: edu20230513
      endpoint: oss-cn-guangzhou.aliyuncs.com
      keyid: LTAI5tDDc7oFqhiZFejDVZtp
      keysecret: UWBM3EChOz3WNt4NiiJ4N8E0dTZH00
  vod:
    file:
      keyid: LTAI5tDDc7oFqhiZFejDVZtp
      keysecret: UWBM3EChOz3WNt4NiiJ4N8E0dTZH00

baidu:
  clientId: 7d8B4sjXqzFIZSItGjzMBPoE
  clientSecret: fMyp1YHdcvI0NrlwfRzKGp740eEkuqVn
gpt:
  token: sk-jss3OsANYgFr6qTbFa1bD4E5399c49C0Ae6f73647fF2E154
gpt2:
  token: sk-Qt2Nf5Nm2XOXCxHW3jsbDcoKfLgDrrwdGm9rCzbQmsccX6rp

server:
  port: 6666
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    password: fdzquckzjlgbdich
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
    username: 2371119023@qq.com
    nickname: "知识问答社区"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 1024MB
  application:
    name: campus-user
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    #配置数据源类型（可有）
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 623718.a
    url: jdbc:mysql://154.12.40.85:3306/wschat?characterEncoding=utf-8&useSSL=false

  redis:
    host: 154.12.40.85
    port: 6379
    database: 0
    timeout: 10000
    connect-timeout: 10000
    password: 623718.a
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0

